services:
  nginx:
    hostname: nginx
    image: nginx:latest
    ports:
        - 8950:8443
    restart: always
    tty: true
    volumes:
      - ./nginx/configs:/etc/nginx/conf.d/
      - ./nginx/keys:/etc/nginx/keys
      - ./nginx/statics:/etc/nginx/static/statics
    depends_on:
      - app
      - auth

  frontend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development-dependencies-env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    restart: always

  app:
    hostname: app
    build:
      context: ./backend
      dockerfile: dockerfile
      target: develop
    volumes:
      - ./backend/src:/app
      - ./backend/received:/received
      - ./shared:/shared
      - ~/.kube/config:/root/.kube/config
    ports:
      - 8090:8090
    env_file:
      - ./config/app.env
      - ./openssl/jwtKeys/public.env
    tty: true
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - default
      - host_network
    entrypoint:
      - /bin/bash
      - -c
      - "ip route add 172.33.0.0/16 via 172.20.0.1 && exec go tool air -c ./.air.toml"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
  builder:
    hostname: builder
    build:
      context: ./builder
      dockerfile: dockerfile
      target: develop
    volumes:
      - ./builder/src:/app
      - ./builder/received:/received
      - ./shared:/shared
      - ~/.kube/config:/root/.kube/config
    ports:
      - 8091:8091
    env_file:
      - ./config/app.env
      - ./openssl/jwtKeys/public.env
    tty: true
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - default
      - host_network
    entrypoint:
      - /bin/bash
      - -c
      - "ip route add 172.33.0.0/16 via 172.20.0.1 && exec go tool air -c ./.air.toml"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  watcher:
    hostname: watcher
    build:
      context: ./watcher
      dockerfile: dockerfile
      target: develop
    volumes:
      - ./watcher/src:/app
      - ./shared:/shared
      - ~/.kube/config:/root/.kube/config
    env_file:
      - ./config/app.env
      - ./openssl/jwtKeys/public.env
    tty: true
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - default
      - host_network
    entrypoint:
      - /bin/bash
      - -c
      - "ip route add 172.33.0.0/16 via 172.20.0.1 && exec go tool air -c ./.air.toml"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  auth:
    hostname: auth
    image: ghcr.io/mattuu0/authbase/auth:latest
    env_file:
      - ./config/auth.env
      - ./openssl/jwtKeys/private.env
    restart: always
    volumes:
      - ./auth/icons:/assets/icons
    depends_on:
      postgres:
        condition: service_started

  migrate:
    image: ghcr.io/mattuu0/authbase/auth:latest
    env_file:
        - ./config/auth.env
    command: ["/auth","migrate","-r"]
    depends_on:
      postgres:
        condition: service_started

  postgres:
    hostname: db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/script/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  dbdata:
    driver: local

networks:
  default:
    driver: bridge
  host_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
 