# https://taskfile.dev

version: '3'

vars:
  COMPOSE: docker compose -f docker-compose.yaml -f docker-compose-temporal.yaml

tasks:
  default:
    cmds:
      - cmd: 'echo "使用可能なタスク: setup, reset, up, down, logs, logs:frontend, logs:backend, release, test-all"'
    silent: true

  # リセットコマンド
  reset:
    cmds:
      - echo "コンテナを削除します"
      - "{{.COMPOSE}} down -v --rmi all"
      - task: setup
    silent: true

  # セットアップするコマンド
  setup:
    cmds:
      - echo "configファイルを生成します"
      - task: config

      - echo "各種カギを生成します"
      - task: genkey

      - echo "コンテナを立ち上げます"
      - "{{.COMPOSE}} up -d"

  # コンテナを起動するコマンド
  up:
    cmds:
      - "{{.COMPOSE}} up -d"

  # コンテナを停止するコマンド
  down:
    cmds:
      - "{{.COMPOSE}} down"

  # カギを生成するコマンド
  genkey:
    cmds:
      - cmd: docker run --rm -it -v .\\openssl\\jwtKeys:/jwtkeys -v .\\nginx\\keys:/sslkeys {{.Build_Image}}
        platforms: [windows]
      - cmd: docker run --rm -it -v ./openssl/jwtKeys:/jwtkeys -v ./nginx/keys:/sslkeys {{.Build_Image}}
        platforms: [linux,darwin]
    vars:
      Build_Image:
        sh: docker build -q ./openssl

  # 設定を更新するコマンド
  config:
    cmds:
      - cmd: docker run --rm -it -v .\\config:/config/data {{.Build_Image}}
        platforms: [windows]
      - cmd: docker run --rm -it -v ./config:/config/data {{.Build_Image}}
        platforms: [linux,darwin]
      - echo "設定用のイメージを削除しています"
      - docker rmi -f {{.Build_Image}}
    vars:
      Build_Image:
        sh: docker build -q ./config

  # release ビルドを行うコマンド
  release:
    cmds:
      - echo "releaseビルドで起動します"
      - docker compose -f docker-compose-build.yaml up -d --remove-orphans --build

  # 全サービスのログを表示
  logs:
    cmds:
      - "{{.COMPOSE}} logs -f"

  # フロントエンドのログを表示
  logs:frontend:
    cmds:
      - "{{.COMPOSE}} logs -f frontend"

  # バックエンドのログを表示
  logs:backend:
    cmds:
      - "{{.COMPOSE}} logs -f handler"

  # テストを実行するコマンド（マイクロサービスごとに順次実行する）
  test-all:
    cmds:
      # イメージをビルドする
      - docker compose -f docker-compose-test.yaml build
      # handler サービスのテストを実行する
      - docker compose -f docker-compose-test.yaml up --abort-on-container-exit --exit-code-from handler-test handler-test postgres-test
      # builder サービスのテストを実行する
      - docker compose -f docker-compose-test.yaml up --abort-on-container-exit --exit-code-from builder-test builder-test
      # watcher サービスのテストを実行する
      - docker compose -f docker-compose-test.yaml up --abort-on-container-exit --exit-code-from watcher-test watcher-test
      # controller サービスのテストを実行する
      - docker compose -f docker-compose-test.yaml up --abort-on-container-exit --exit-code-from controller-test controller-test
      # テスト終了後にコンテナとボリュームを削除する
      - docker compose -f docker-compose-test.yaml down -v
