FROM golang:1.26-bookworm as develop

RUN apt update && apt install curl wget git iproute2 -y

WORKDIR /app

COPY ./src/go.mod .

# go.mod only (no dependency download yet, shared module is mounted at runtime)
