import type { TutorialStep } from './types' // ステップ型をインポートする

// チュートリアルの全ステップ定義（データ駆動）
// page フィールドの `:id` セグメントは useTutorial でワイルドカードとして扱われる
export const TUTORIAL_STEPS: TutorialStep[] = [

  // ══════════════════════════════════════════
  // 基本チュートリアル
  // ══════════════════════════════════════════
  {
    id: 'welcome',
    targetId: null,
    placement: 'center',
    page: '/',
    track: 'basic',
    title: 'launchs へようこそ！',
    body: 'このチュートリアルでは、プロジェクトの作成からアプリの外部公開まで一通りの手順を案内します。各画面で重要な操作箇所をハイライトするので、指示に従って進めてください。',
    showGlossary: true,
  },
  {
    id: 'new-project-button',
    targetId: 'tutorial-new-project-btn',
    placement: 'bottom',
    page: '/',
    track: 'basic',
    title: 'プロジェクトを作成しましょう',
    body: '「New Project」ボタンをクリックして、最初のプロジェクトを作成します。プロジェクトはデプロイメントやネットワーク設定をまとめる管理単位です。',
  },
  {
    id: 'project-name-input',
    targetId: 'tutorial-project-name-input',
    placement: 'right',
    page: '/projects/new',
    track: 'basic',
    title: 'プロジェクト名を入力してください',
    body: '英小文字・数字・ハイフンを使ってプロジェクト名を付けてください（例：my-app）。',
  },
  {
    id: 'project-create-button',
    targetId: 'tutorial-project-create-btn',
    placement: 'top',
    page: '/projects/new',
    track: 'basic',
    title: '「Create Project」で作成します',
    body: '名前を入力したら「Create Project」ボタンをクリックしてプロジェクトを作成してください。作成するとプロジェクトの画面に移動します。',
  },
  {
    id: 'add-deployment-button',
    targetId: 'tutorial-add-button',
    placement: 'bottom',
    page: '/projects/:id',
    track: 'basic',
    title: 'デプロイメントを追加しましょう',
    body: '「追加」ボタンをクリックしてください。メニューが開きます。',
  },
  {
    id: 'add-deployment-menu',
    targetId: 'tutorial-add-deployment-menu',
    placement: 'left',
    page: '/projects/:id',
    track: 'basic',
    title: '「Deployment」を選択してください',
    body: 'メニューから「Deployment」をクリックすると、デプロイメントの作成画面に移動します。',
    autoAdvanceOnAppear: true,
  },
  {
    id: 'deployment-type-select',
    targetId: 'tutorial-deployment-type-image',
    placement: 'bottom',
    page: '/projects/:id/deployments/new',
    track: 'basic',
    title: 'Container Image を選択してください',
    body: '「Container Image」を選択すると、Docker イメージのURLを直接指定してデプロイできます。まずは「nginx:latest」などの公開イメージで試してみましょう。',
  },
  {
    id: 'deployment-name-input',
    targetId: 'tutorial-deployment-name-input',
    placement: 'bottom',
    page: '/projects/:id/deployments/new',
    track: 'basic',
    title: 'デプロイメント名を入力してください',
    body: '英小文字・数字・ハイフンを使ってデプロイメント名を付けてください（例：my-app）。',
  },
  {
    id: 'deployment-image-input',
    targetId: 'tutorial-deployment-image-input',
    placement: 'bottom',
    page: '/projects/:id/deployments/new',
    track: 'basic',
    title: 'イメージURLを入力してください',
    body: '使用する Docker イメージを指定します。例えば「nginx:latest」と入力すると、nginx の最新版がデプロイされます。',
  },
  {
    id: 'deployment-create-button',
    targetId: 'tutorial-deployment-create-btn',
    placement: 'top',
    page: '/projects/:id/deployments/new',
    track: 'basic',
    title: '「デプロイメントを作成」を押してください',
    body: '設定が完了したら「デプロイメントを作成」ボタンを押してください。作成後はプロジェクト画面に自動で戻ります。',
  },
  {
    id: 'deployment-open-card',
    targetId: 'tutorial-deployment-card',
    placement: 'right',
    page: '/projects/:id',
    track: 'basic',
    title: 'デプロイメントを開いてください',
    body: '作成したデプロイメントのカードをクリックすると、設定画面が開きます。',
    autoAdvanceOnAppear: true,
  },
  {
    id: 'deployment-networking-tab',
    targetId: 'tutorial-deployment-networking-tab',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'basic',
    title: 'ネットワークタブを開いてください',
    body: '「ネットワーク」タブをクリックすると、ポート設定ができます。外部からアクセスするにはポートの設定が必要です。',
  },
  {
    id: 'deployment-port-input',
    targetId: 'tutorial-deployment-port-input',
    placement: 'top',
    page: '/projects/:id/deployments/:depId',
    track: 'basic',
    title: 'ポート（外部）を入力してください',
    body: 'コンテナが外部に公開するポート番号を入力します。nginx など HTTP サーバーなら「80」が一般的です。',
  },
  {
    id: 'deployment-target-port-input',
    targetId: 'tutorial-deployment-target-port-input',
    placement: 'top',
    page: '/projects/:id/deployments/:depId',
    track: 'basic',
    title: 'ターゲットポートを入力してください',
    body: 'コンテナ内部でアプリが実際に待ち受けているポート番号を入力します。ポート（外部）と同じ値で構いません（例：80）。',
  },
  {
    id: 'deployment-service-save',
    targetId: 'tutorial-deployment-service-save',
    placement: 'top',
    page: '/projects/:id/deployments/:depId',
    track: 'basic',
    title: '「Serviceを設定」を押してください',
    body: 'ポートを入力したら「Serviceを設定」ボタンを押して保存します。',
  },
  {
    id: 'deployment-envvars-tab',
    targetId: 'tutorial-deployment-envvars-tab',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'basic',
    title: '環境変数タブについて',
    body: '「環境変数」タブでは、コンテナに渡す設定値（APIキーやDBパスワードなど）を管理できます。シークレットとして登録するとマスクされます。今回はスキップして次へ進みます。',
  },
  {
    id: 'deployment-volumes-tab',
    targetId: 'tutorial-deployment-volumes-tab',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'basic',
    title: 'ボリュームタブについて',
    body: '「ボリューム」タブでは、コンテナが再起動しても消えない永続ストレージを管理できます。データベースのデータ保存などに使います。今回はスキップして次へ進みます。',
  },
  {
    id: 'deployment-history-tab',
    targetId: 'tutorial-deployment-history-tab',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'basic',
    title: '履歴タブについて',
    body: '「履歴」タブでは、過去の Apply 操作の履歴を確認できます。いつ誰がどんな変更を適用したかを追跡できます。今回はスキップして次へ進みます。',
  },
  {
    id: 'deployment-apply-button',
    targetId: 'tutorial-deployment-apply-btn',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'basic',
    title: 'Apply でデプロイを実行しましょう',
    body: '「Apply」ボタンを押すと、設定が Kubernetes に反映されてアプリが起動します。ポート設定も含めて一括で適用されます。',
  },
  {
    id: 'deployment-close-sidebar',
    targetId: 'tutorial-deployment-close-btn',
    placement: 'left',
    page: '/projects/:id',
    track: 'basic',
    title: 'サイドバーを閉じてください',
    body: '右上の「×」ボタンをクリックしてデプロイメント設定を閉じてください。次は外部公開のための IngressRoute を作成します。',
  },
  {
    id: 'ingress-creation',
    targetId: 'tutorial-add-button',
    placement: 'bottom',
    page: '/projects/:id',
    track: 'basic',
    title: 'IngressRoute で外部公開しましょう',
    body: '「追加」ボタンをクリックしてください。メニューが開きます。',
  },
  {
    id: 'ingress-menu',
    targetId: 'tutorial-add-ingress-menu',
    placement: 'left',
    page: '/projects/:id',
    track: 'basic',
    title: '「IngressRoute」を選択してください',
    body: 'メニューから「IngressRoute」をクリックすると、外部公開用のURLが自動で作成され、設定サイドバーが開きます。',
    autoAdvanceOnAppear: true,
  },
  {
    id: 'ingress-overview',
    targetId: 'tutorial-ingress-host',
    placement: 'bottom',
    page: '/projects/:id',
    track: 'basic',
    title: 'IngressRoute が作成されました',
    body: 'ホスト名が自動で割り当てられました。このURLがアプリの外部公開アドレスになります。次はパスルールを設定して、どのデプロイメントにトラフィックを転送するか指定します。',
  },
  {
    id: 'ingress-paths-tab',
    targetId: 'tutorial-ingress-paths-tab',
    placement: 'bottom',
    page: '/projects/:id',
    track: 'basic',
    title: 'パスルールタブを開いてください',
    body: '「パスルール」タブをクリックすると、URLのパスごとにどのデプロイメントへ転送するか設定できます。',
  },
  {
    id: 'ingress-service-select',
    targetId: 'tutorial-ingress-service-select',
    placement: 'top',
    page: '/projects/:id',
    track: 'basic',
    title: '転送先のデプロイメントを選択してください',
    body: '「転送先 Service」のドロップダウンから、先ほど作成したデプロイメントを選択してください。',
  },
  {
    id: 'ingress-add-path-rule',
    targetId: 'tutorial-ingress-add-path-rule',
    placement: 'top',
    page: '/projects/:id',
    track: 'basic',
    title: '「追加」を押してパスルールを登録してください',
    body: '「追加」ボタンを押すとパスルールが保存されます。これで「/」へのアクセスがデプロイメントに転送されます。',
  },
  {
    id: 'ingress-apply',
    targetId: 'tutorial-ingress-apply-btn',
    placement: 'bottom',
    page: '/projects/:id',
    track: 'basic',
    title: 'Apply で外部公開を反映しましょう',
    body: '「Apply」ボタンを押すと、パスルールが Kubernetes に反映されてアプリが外部公開されます。',
  },
  {
    id: 'complete',
    targetId: null,
    placement: 'center',
    page: '/projects/:id',
    track: 'basic',
    title: 'チュートリアル完了！',
    body: 'お疲れ様でした！基本的な流れをマスターしました。さらに「ストレージ」「環境変数」「リソースQuota」のアドバンスチュートリアルも画面右下の「？」ボタンから始められます。',
  },

  // ══════════════════════════════════════════
  // アドバンス：ストレージ（ボリューム）
  // ══════════════════════════════════════════
  {
    id: 'adv-storage-intro',
    targetId: null,
    placement: 'center',
    page: '/projects/:id',
    track: 'adv-storage',
    title: 'ストレージ（ボリューム）チュートリアル',
    body: 'ボリュームはコンテナが再起動しても消えない永続ストレージです。データベースのデータ保存などに使います。このチュートリアルでは、ボリュームの作成とデプロイメントへのマウントを行います。',
  },
  {
    id: 'adv-storage-add-button',
    targetId: 'tutorial-add-button',
    placement: 'bottom',
    page: '/projects/:id',
    track: 'adv-storage',
    title: '「追加」ボタンをクリックしてください',
    body: 'ボリュームを追加するには「追加」ボタンからメニューを開きます。',
  },
  {
    id: 'adv-storage-menu',
    targetId: 'tutorial-add-volume-menu',
    placement: 'left',
    page: '/projects/:id',
    track: 'adv-storage',
    title: '「Volume」を選択してください',
    body: 'メニューから「Volume」をクリックするとボリュームの設定サイドバーが開きます。',
    autoAdvanceOnAppear: true,
  },
  {
    id: 'adv-storage-form',
    targetId: 'tutorial-volume-name-input',
    placement: 'right',
    page: '/projects/:id',
    track: 'adv-storage',
    title: 'ボリューム名を入力してください',
    body: '英小文字・数字・ハイフンでボリューム名を付けてください（例：my-data）。',
  },
  {
    id: 'adv-storage-size',
    targetId: 'tutorial-volume-size-input',
    placement: 'right',
    page: '/projects/:id',
    track: 'adv-storage',
    title: 'サイズ（MB）を入力してください',
    body: '確保するストレージ容量をMB単位で入力します（例：1024 = 1GB）。一度作成するとサイズは変更できないのでご注意ください。',
  },
  {
    id: 'adv-storage-create',
    targetId: 'tutorial-volume-create-btn',
    placement: 'top',
    page: '/projects/:id',
    track: 'adv-storage',
    title: 'ボリュームを作成してください',
    body: '「ボリュームを作成」ボタンを押してボリュームを保存します。',
  },
  {
    id: 'adv-storage-open-card',
    targetId: 'tutorial-deployment-card',
    placement: 'right',
    page: '/projects/:id',
    track: 'adv-storage',
    title: 'デプロイメントを開いてください',
    body: '基本チュートリアルで作成した nginx デプロイメントのカードをクリックして、設定画面を開きます。',
    autoAdvanceOnAppear: true,
  },
  {
    id: 'adv-storage-mount-tab',
    targetId: 'tutorial-deployment-volumes-tab',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-storage',
    title: 'ボリュームタブを開いてください',
    body: '「ボリューム」タブをクリックすると、デプロイメントにマウントするボリュームを設定できます。',
  },
  {
    id: 'adv-storage-mount-select',
    targetId: 'tutorial-volume-mount-select',
    placement: 'top',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-storage',
    title: 'マウントするボリュームを選択してください',
    body: 'ドロップダウンから先ほど作成したボリュームを選択します。',
  },
  {
    id: 'adv-storage-mount-path',
    targetId: 'tutorial-volume-mount-path',
    placement: 'top',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-storage',
    title: 'マウントパスを入力してください',
    body: 'コンテナ内でボリュームをどのパスにマウントするか指定します。例えば「/data」と入力すると、コンテナの /data ディレクトリがボリュームに紐付きます。',
  },
  {
    id: 'adv-storage-mount-add',
    targetId: 'tutorial-volume-mount-add-btn',
    placement: 'top',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-storage',
    title: '「マウントを追加」を押してください',
    body: 'ボリュームとマウントパスを入力したら「マウントを追加」ボタンを押して保存します。',
  },
  {
    id: 'adv-storage-apply',
    targetId: 'tutorial-deployment-apply-btn',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-storage',
    title: 'Apply でボリュームマウントを反映しましょう',
    body: '「Apply」ボタンを押すとボリュームマウント設定が Kubernetes に反映されます。',
  },
  {
    id: 'adv-storage-complete',
    targetId: null,
    placement: 'center',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-storage',
    title: 'ストレージチュートリアル完了！',
    body: 'ボリュームの作成とマウントが完了しました。コンテナを再起動してもデータが保持されます。',
  },

  // ══════════════════════════════════════════
  // アドバンス：環境変数
  // ══════════════════════════════════════════
  {
    id: 'adv-envvar-intro',
    targetId: null,
    placement: 'center',
    page: '/projects/:id',
    track: 'adv-envvar',
    title: '環境変数チュートリアル',
    body: '環境変数はコンテナに渡す設定値です。APIキー・データベース接続情報・フラグなどをコードに埋め込まずに管理できます。シークレットとして登録するとマスクされて安全に保管されます。',
  },
  {
    id: 'adv-envvar-add-button',
    targetId: 'tutorial-add-button',
    placement: 'bottom',
    page: '/projects/:id',
    track: 'adv-envvar',
    title: '「追加」ボタンをクリックしてください',
    body: '環境変数を追加するには「追加」ボタンからメニューを開きます。',
  },
  {
    id: 'adv-envvar-menu',
    targetId: 'tutorial-add-envvar-menu',
    placement: 'left',
    page: '/projects/:id',
    track: 'adv-envvar',
    title: '「EnvVar」を選択してください',
    body: 'メニューから「EnvVar」をクリックすると環境変数の設定サイドバーが開きます。',
    autoAdvanceOnAppear: true,
  },
  {
    id: 'adv-envvar-form',
    targetId: 'tutorial-envvar-key-input',
    placement: 'right',
    page: '/projects/:id',
    track: 'adv-envvar',
    title: 'キー名を入力してください',
    body: '環境変数のキー名を大文字・アンダースコア形式で入力します（例：DATABASE_URL、API_KEY）。コンテナ内でこの名前で参照されます。',
  },
  {
    id: 'adv-envvar-value',
    targetId: 'tutorial-envvar-value-input',
    placement: 'right',
    page: '/projects/:id',
    track: 'adv-envvar',
    title: '値を入力してください',
    body: '環境変数に設定する値を入力します。シークレットにチェックを入れると入力がマスクされ、k8s Secret として安全に保管されます。',
  },
  {
    id: 'adv-envvar-secret',
    targetId: 'tutorial-envvar-secret-checkbox',
    placement: 'right',
    page: '/projects/:id',
    track: 'adv-envvar',
    title: 'シークレットについて',
    body: 'パスワードやAPIキーなど機密情報の場合は「シークレット」にチェックを入れてください。k8s Secret に格納され、管理画面でも値がマスクされます。今回はチェックを入れずに次へ進んでも構いません。',
  },
  {
    id: 'adv-envvar-create',
    targetId: 'tutorial-envvar-create-btn',
    placement: 'top',
    page: '/projects/:id',
    track: 'adv-envvar',
    title: '「作成」を押してください',
    body: 'キーと値を入力したら「作成」ボタンを押して環境変数を保存します。',
  },
  {
    id: 'adv-envvar-open-card',
    targetId: 'tutorial-deployment-card',
    placement: 'right',
    page: '/projects/:id',
    track: 'adv-envvar',
    title: 'デプロイメントを開いてください',
    body: '作成した環境変数をデプロイメントに適用するには、デプロイメントのカードをクリックして設定画面を開きます。',
    autoAdvanceOnAppear: true,
  },
  {
    id: 'adv-envvar-mount-tab',
    targetId: 'tutorial-deployment-envvars-tab',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-envvar',
    title: '環境変数タブを開いてください',
    body: '「環境変数」タブをクリックすると、デプロイメントにマウントする環境変数を設定できます。',
  },
  {
    id: 'adv-envvar-mount-select',
    targetId: 'tutorial-envvar-mount-select',
    placement: 'top',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-envvar',
    title: 'マウントする環境変数を選択してください',
    body: 'ドロップダウンから先ほど作成した環境変数を選択します。',
  },
  {
    id: 'adv-envvar-mount-add',
    targetId: 'tutorial-envvar-mount-add-btn',
    placement: 'top',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-envvar',
    title: '「マウントを追加」を押してください',
    body: '環境変数を選択したら「マウントを追加」ボタンを押して保存します。',
  },
  {
    id: 'adv-envvar-apply',
    targetId: 'tutorial-deployment-apply-btn',
    placement: 'bottom',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-envvar',
    title: 'Apply で環境変数を反映しましょう',
    body: '「Apply」ボタンを押すと環境変数がコンテナに渡されます。',
  },
  {
    id: 'adv-envvar-complete',
    targetId: null,
    placement: 'center',
    page: '/projects/:id/deployments/:depId',
    track: 'adv-envvar',
    title: '環境変数チュートリアル完了！',
    body: '環境変数の作成とマウントが完了しました。コードを変更せずに設定値を管理できます。',
  },

  // ══════════════════════════════════════════
  // アドバンス：リソースQuota
  // ══════════════════════════════════════════
  {
    id: 'adv-quota-intro',
    targetId: null,
    placement: 'center',
    page: '/',
    track: 'adv-quota',
    title: 'リソースQuota チュートリアル',
    body: 'リソースQuotaは、プロジェクト全体で使用できるインスタンス数やボリューム容量の上限です。画面下部のフッターで現在の使用状況をいつでも確認できます。',
  },
  {
    id: 'adv-quota-footer',
    targetId: 'tutorial-quota-footer',
    placement: 'top',
    page: '/',
    track: 'adv-quota',
    title: 'リソース使用状況を確認してください',
    body: '画面下部にインスタンスサイズ別の使用数・上限、ボリューム容量の合計が表示されています。80%を超えると警告色になります。上限に近づいたら不要なデプロイメントを削除してリソースを解放しましょう。',
  },
  {
    id: 'adv-quota-complete',
    targetId: null,
    placement: 'center',
    page: '/',
    track: 'adv-quota',
    title: 'リソースQuota チュートリアル完了！',
    body: 'リソース使用状況の確認方法を理解しました。定期的にチェックして、リソース不足によるデプロイ失敗を防ぎましょう。',
  },
]

// トラック別の開始インデックスを返す
export function getTrackStartIndex(track: import('./types').TutorialTrack): number {
  const firstStep = TUTORIAL_STEPS.findIndex(step => step.track === track)
  return firstStep >= 0 ? firstStep : 0
}

// 指定インデックスのトラック内での位置（1始まり）と合計数を返す
export function getTrackProgress(globalIndex: number): { current: number; total: number } {
  const track = TUTORIAL_STEPS[globalIndex]?.track
  if (!track) return { current: 1, total: 1 }
  const trackSteps = TUTORIAL_STEPS.filter(step => step.track === track) // 同一トラックのステップ一覧
  const trackStart = TUTORIAL_STEPS.findIndex(step => step.track === track) // トラック開始インデックス
  return {
    current: globalIndex - trackStart + 1, // トラック内での現在位置
    total: trackSteps.length, // トラックの総ステップ数
  }
}
