# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Builder

on:
  push:
    branches:
      - "**"
    paths:
      - "builder/**"
      - "shared/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "builder/**"
      - "shared/**"

jobs:
  test:
    name: builder テスト
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Task をインストール
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: builder サービスのテストを実行
        run: task test:builder

      - name: テスト用コンテナを削除
        if: always()
        run: docker compose -f docker-compose-test.yaml down -v
